# Generated by Django 4.2.6 on 2024-08-29 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.IntegerField(max_length=11)),
                ('landline_phone', models.IntegerField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HouseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='HomeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meterage', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('wc', models.IntegerField()),
                ('mortage_price', models.IntegerField()),
                ('rental_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('about', models.TextField()),
                ('phonehome', models.IntegerField(max_length=11)),
                ('image', models.ImageField(upload_to='images/home/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(to='web.image')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.housemodel')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.housecategory')),
            ],
        ),
    ]
