# Generated by Django 4.2.6 on 2024-08-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homefile',
            name='bathroom',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='homefile',
            name='meterage',
            field=models.IntegerField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='homefile',
            name='rooms',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='homefile',
            name='wc',
            field=models.IntegerField(max_length=10),
        ),
    ]
