# Generated by Django 4.2.6 on 2024-08-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_homefile_bathroom_alter_homefile_meterage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housecategory',
            old_name='type',
            new_name='name',
        ),
    ]
