# Generated by Django 4.2.6 on 2024-08-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_type_housecategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homefile',
            name='images',
        ),
        migrations.AddField(
            model_name='homefile',
            name='image2',
            field=models.ImageField(default=1, upload_to='images/home/2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homefile',
            name='image3',
            field=models.ImageField(null=True, upload_to='images/home/3'),
        ),
        migrations.AddField(
            model_name='homefile',
            name='image4',
            field=models.ImageField(null=True, upload_to='images/home/4'),
        ),
        migrations.AddField(
            model_name='homefile',
            name='image5',
            field=models.ImageField(null=True, upload_to='images/home/5'),
        ),
        migrations.AlterField(
            model_name='homefile',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='homefile',
            name='bathroom',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='homefile',
            name='meterage',
            field=models.IntegerField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='homefile',
            name='phonehome',
            field=models.IntegerField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='homefile',
            name='rooms',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='homefile',
            name='wc',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
