# Generated by Django 4.2.6 on 2024-08-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_homefile_images_homefile_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homefile',
            name='image5',
        ),
        migrations.AlterField(
            model_name='estate',
            name='landline_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estate',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='homefile',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='homefile',
            name='bathroom',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='homefile',
            name='meterage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='homefile',
            name='phonehome',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='homefile',
            name='rooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='homefile',
            name='wc',
            field=models.IntegerField(null=True),
        ),
    ]
