# Generated by Django 4.2.6 on 2024-09-01 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0005_remove_homefile_image5_alter_estate_landline_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homefile',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
