# Generated by Django 4.2.6 on 2025-05-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='star',
        ),
        migrations.AddField(
            model_name='product',
            name='category_clothes',
            field=models.ManyToManyField(to='website.category_clothes'),
        ),
    ]
