# Generated by Django 4.2.6 on 2025-04-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usersite',
            name='phon',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usersite',
            name='post_code',
            field=models.IntegerField(),
        ),
    ]
