# Generated by Django 4.2.6 on 2025-05-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
