# Generated by Django 4.2.6 on 2024-03-24 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=100, null=True)),
                ('bestphoto', models.ImageField(null=True, upload_to='media/photocity/%Y/%m/%d')),
                ('address_restaurants', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spectacular_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('photo', models.ImageField(null=True, upload_to='media/photolocation/%Y/%m/%d')),
                ('description', models.TextField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.city')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('restaurantphoto', models.ImageField(null=True, upload_to='media/photorestaurants/%Y/%m/%d')),
                ('description', models.TextField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.city')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('htelphoto', models.ImageField(null=True, upload_to='media/photohotel/%Y/%m/%d')),
                ('description', models.TextField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.city')),
            ],
        ),
    ]
