# Generated by Django 4.2.6 on 2024-03-29 19:14

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_city_address_restaurants_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/Comment/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='about',
            field=models.CharField(choices=[(web.models.Restaurants, 'Restaurants'), (web.models.Spectacular_location, 'Spectacular_location'), (web.models.Hotel, 'Hotel')], max_length=50),
        ),
    ]
