# Generated by Django 4.2.6 on 2024-08-25 17:53

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_comment_photo_alter_comment_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='about',
            field=models.CharField(choices=[(web.models.Hotel, 'Hotel'), (web.models.Spectacular_location, 'Spectacular_location'), (web.models.Restaurants, 'Restaurants')], max_length=50),
        ),
    ]
