# Generated by Django 4.2.6 on 2024-08-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_comment_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='about',
        ),
        migrations.AddField(
            model_name='comment',
            name='about',
            field=models.ManyToManyField(to='web.city'),
        ),
    ]
