# Generated by Django 4.2.6 on 2024-01-11 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='concertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True, verbose_name='نام کنسرت')),
                ('SingerName', models.CharField(max_length=100, null=True, verbose_name='خواننده')),
                ('lenght', models.IntegerField(null=True, verbose_name='مدت زمان')),
                ('Poster', models.ImageField(null=True, upload_to='concertImages/', verbose_name='پوستر')),
            ],
        ),
        migrations.CreateModel(
            name='locationModel',
            fields=[
                ('IdNumber', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد محل')),
                ('Name', models.CharField(max_length=100, null=True, verbose_name='نام محل')),
                ('Address', models.CharField(default='تهران-برج میلاد', max_length=500, null=True, verbose_name='آدرس')),
                ('Phone', models.CharField(max_length=11, null=True, verbose_name='تلفن')),
                ('capacity', models.IntegerField(null=True, verbose_name='ظرفیت')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Family', models.CharField(max_length=100)),
                ('ProfileImage', models.ImageField(upload_to='ProfileImages/')),
                ('Gender', models.IntegerField(choices=[('Man', 'مرد'), ('Woman', 'زن')])),
            ],
        ),
        migrations.CreateModel(
            name='timeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDateTime', models.DateTimeField(verbose_name='تاریخ برگزاری')),
                ('Seats', models.IntegerField(verbose_name='تعداد صندلی')),
                ('Status', models.IntegerField(choices=[(1, 'فروش بلیط شروع شده است'), (2, 'فروش بلیط تمام شده است'), (3, 'این سانی کنسل شده است'), (4, 'در حال فروش بلیط')], verbose_name='وضعیت')),
                ('concertModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.concertmodel', verbose_name='کنسرت')),
                ('locationModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.locationmodel', verbose_name='محل برگزاری')),
            ],
        ),
        migrations.CreateModel(
            name='ticketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketImage', models.ImageField(upload_to='TicketImages/', verbose_name='عکس')),
                ('Name', models.CharField(max_length=100, verbose_name='عنوان')),
                ('Price', models.IntegerField(verbose_name='مبلغ')),
                ('ProfileModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.profilemodel', verbose_name='کاربر')),
                ('timeModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.timemodel', verbose_name='سانس')),
            ],
        ),
    ]
