# Generated by Django 4.2.6 on 2025-04-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_category_contact_special_itmes_drinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_itmes',
            name='imge',
            field=models.ImageField(null=True, upload_to='images/special/'),
        ),
    ]
