# Generated by Django 4.2.6 on 2025-04-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_cafe_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='price',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='special_itmes',
            name='price',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
