# Generated by Django 4.2.6 on 2025-04-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_drinks_price_alter_special_itmes_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='special_itmes',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
