# Generated by Django 4.2.6 on 2025-07-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameMall', models.CharField(max_length=400)),
                ('address', models.TextField()),
                ('call', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('Linkinstegram', models.CharField(max_length=2000)),
                ('Linkfacebook', models.CharField(max_length=2000)),
                ('Linktwitter', models.CharField(max_length=2000)),
                ('LinklinkedIn', models.CharField(max_length=2000)),
            ],
        ),
    ]
