# Generated by Django 4.2.6 on 2024-04-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progarmmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(max_length=100)),
                ('languages_persian', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='aboutexperience_persian',
            field=models.TextField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='resume',
            name='abuotinstitute_persian',
            field=models.TextField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='experiencename_persian',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='namecity_persian',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='nameinstitute_persian',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.RemoveField(
            model_name='resume',
            name='language',
        ),
        migrations.AddField(
            model_name='resume',
            name='language',
            field=models.ManyToManyField(to='progarmmer.language'),
        ),
    ]
