# Generated by Django 4.2.6 on 2024-04-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progarmmer', '0002_language_resume_aboutexperience_persian_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_skill', models.CharField(max_length=100)),
                ('professional_skill_persian', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='abuotproject_persian',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='nameproject_persian',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='resume',
            name='professional_skill',
        ),
        migrations.AddField(
            model_name='resume',
            name='professional_skill',
            field=models.ManyToManyField(to='progarmmer.professional_skill'),
        ),
    ]
