# Generated by Django 4.2.6 on 2024-04-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progarmmer', '0003_professional_skill_project_abuotproject_persian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='abuotproject_persian',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='nameproject_persian',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='abuotinstitute_persian',
            field=models.TextField(default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='resume',
            name='namecity',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='namecity_persian',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='nameinstitute_persian',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
