# Generated by Django 4.2.6 on 2024-04-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progarmmer', '0004_alter_project_abuotproject_persian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='language',
            field=models.ManyToManyField(related_name='language', to='progarmmer.language'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='professional_skill',
            field=models.ManyToManyField(related_name='skill', to='progarmmer.professional_skill'),
        ),
    ]
