# Generated by Django 4.2.6 on 2024-04-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progarmmer', '0006_remove_language_languages_persian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language_persian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages_persian', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professional_skill_persian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_skill_persian', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='professional_skill',
            name='professional_skill_persian',
        ),
        migrations.AddField(
            model_name='resume',
            name='language_persian',
            field=models.ManyToManyField(related_name='language_persian', to='progarmmer.language_persian'),
        ),
        migrations.AddField(
            model_name='resume',
            name='professional_skill_persian',
            field=models.ManyToManyField(related_name='skill_persian', to='progarmmer.professional_skill_persian'),
        ),
    ]
