# Generated by Django 4.2.6 on 2024-04-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progarmmer', '0007_language_persian_professional_skill_persian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='language_persian',
            field=models.ManyToManyField(related_name='l_persian', to='progarmmer.language_persian'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='professional_skill_persian',
            field=models.ManyToManyField(related_name='s_persian', to='progarmmer.professional_skill_persian'),
        ),
    ]
