# Generated by Django 4.2.6 on 2024-04-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progarmmer', '0010_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.AddField(
            model_name='abuot',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='abuot',
            name='github_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abuot',
            name='linkedin_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abuot',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
