# Generated by Django 4.2.6 on 2024-08-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default='blog/static/img/about-img.jpg', upload_to='blog/'),
        ),
    ]
