# Generated by Django 4.2.6 on 2025-08-05 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('aboutus', models.TextField()),
                ('adress', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('addressF', models.CharField(max_length=500)),
                ('addressI', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('aboutus', models.TextField()),
                ('address', models.TextField(max_length=500)),
                ('photo', models.ImageField(upload_to='media/photos/branches')),
                ('more_photo1', models.ImageField(upload_to='media/photos/branches')),
                ('more_photo2', models.ImageField(upload_to='media/photos/branches')),
                ('more_photo3', models.ImageField(upload_to='media/photos/branches')),
                ('more_photo4', models.ImageField(upload_to='media/photos/branches')),
                ('more_photo5', models.ImageField(upload_to='media/photos/branches')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing_off',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prise_off', models.IntegerField()),
                ('meno', models.CharField(choices=[('starter', 'Starter'), ('dish', 'Dish'), ('desert', 'Desert'), ('dreink', 'Dreink')], max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.branches')),
            ],
        ),
        migrations.CreateModel(
            name='Meno_starter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter', models.CharField(max_length=50)),
                ('prise', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/photos/meno')),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.branches')),
            ],
        ),
        migrations.CreateModel(
            name='Meno_dreink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dreink', models.CharField(max_length=50)),
                ('prise', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/photos/meno/dreink')),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.branches')),
            ],
        ),
        migrations.CreateModel(
            name='Meno_dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=50)),
                ('prise', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/photos/meno/dish')),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.branches')),
            ],
        ),
        migrations.CreateModel(
            name='Meno_desert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desert', models.CharField(max_length=50)),
                ('prise', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/photos/meno/desert')),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.branches')),
            ],
        ),
    ]
