# Generated by Django 4.2.6 on 2025-08-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meno_desert',
            old_name='prise',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='meno_dish',
            old_name='prise',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='meno_dreink',
            old_name='prise',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='meno_starter',
            old_name='prise',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='pricing_off',
            old_name='prise_off',
            new_name='price_off',
        ),
    ]
